apiVersion: v1
kind: Service
metadata:
  name: cii-modas-service
spec:
  selector:
    app: cii-modas-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer  # Ou NodePort
