apiVersion: apps/v1
kind: Deployment
metadata:
  name: cii-modas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cii-modas
  template:
    metadata:
      labels:
        app: cii-modas
    spec:
      containers:
        - name: cii-modas-container
          image: cii-modas:latest  # Usando a imagem local
          ports:
            - containerPort: 8082
